alias bload="source ~/.bashrc"
alias bedit="vi ~/.bash_aliases"

alias nvme="sudo nvme"
alias dmesg="sudo dmesg"

alias tmux="tmux -u"
alias vi="nvim"
alias vim="nvim"
alias vimdiff="nvim -d"

alias aptin="sudo apt install -y"
alias aptcs="sudo apt-cache search"
alias aptup="sudo apt update -y && sudo apt upgrade -y"
alias aptrm="sudo apt remove -y"

alias mymutt="cdl && neomutt -d 2 -F ~/.lkml/muttrc"

SRC_PUB="${HOME}/src/public"
DUMP_DIR=${HOME}/dump

alias cdl="cd ${SRC_PUB}/linux"
alias cdf="cd ${SRC_PUB}/fio"
alias cdh="cd ${SRC_PUB}/helper_scripts"
alias cdhu="cd ${SRC_PUB}/helper_scripts/ubuntu"
alias cdlu="cd ${SRC_PUB}/src/public/liburing"

alias kernel_compile_install="time kernel_compile_install"
alias kernel_recompile_install="time kernel_recompile_install"
# export NOTMUCH_CONFIG=$HOME/.lkml/notmuch.rc


function blog_compile() {
	bundle exec jekyll build -d docs
}

function blog_clean() {
	bundle exec jekyll clean
}

function blog_recompile() {
	blog_clean
	blog_compile
}

function host_mnt() {
	set -e
	mod_dir=/lib/modules/$(uname -r)
	sudo mkdir -p $mod_dir
	sudo mount -t 9p -o trans=virtio host_module $mod_dir
}

function reveal_view() {
	if ! command wslview -v; then
		sudo apt install -y wslu
	fi
	wslview http://localhost:8000
}

function kernel_install() {
	set -e
	sudo ls
	sudo make headers_install INSTALL_HDR_PATH=/usr
	sudo make modules_install INSTALL_MOD_STRIP=1
	sudo make install
	make kernelrelease > $DUMP_DIR/kernel.txt
	echo compiled kernel $(cat $DUMP_DIR/kernel.txt)
	echo booted kernel $(uname -r)
	set +e
	echo "Kernel Installation Complete"
}

function kernel_compile() {
	make -j $(getconf _NPROCESSORS_ONLN)
	make kernelrelease > $DUMP_DIR/kernel.txt
	echo compiled_kernel $(cat $DUMP_DIR/kernel.txt)
	echo booted kernel $(uname -r)
	echo "Kernel compilation Complete"
}

function kernel_reconfig() {
	sudo make distclean
	./scripts/kconfig/streamline_config.pl > config_strip
	if [ -f config ]; then
		mv config config_bkp
	fi
	cp config_strip config
	make olddefconfig
	# make tinyconfig
	scripts/config --disable LOCALVERSION_AUTO
	scripts/config --disable LOCALVERSION
	scripts/config --disable DEBUG_INFO
	scripts/config --disable SYSTEM_TRUSTED_KEYS
	scripts/config --disable SYSTEM_TRUSTED_KEYRING
	scripts/config --disable SYSTEM_REVOCATION_KEYS
	scripts/config --disable DEBUG_INFO_BTF
	scripts/config --module BLK_DEV_NVME
	scripts/config --module NVME_TCP
	scripts/config --module NVME_TARGET
	scripts/config --module NVME_TARGET_LOOP
	scripts/config --module NVME_TARGET_TCP
	# scripts/config --disable HEADERS_INSTALL
	# scripts/config --disable SAMPLE_VFS
	echo "Kernel reconfig Complete"
}

function kernel_compile_install() {
	kernel_compile
	kernel_install
}

function kernel_recompile_install() {
	kernel_reconfig
	kernel_compile
	kernel_install
}

function 22_uvm() {
	local QEMU=${HOME}/src/qemu/build/qemu-system-x86_64
	local UBUNTU=${HOME}/qemu_vm/ubuntu-22.04-minimal-cloudimg-amd64.img
	local BASE=${HOME}/qemu_vm/ubuntu.qcow2
	local KERNEL=${HOME}/src/linux/arch/x86/boot/bzImage
	local INITRD=${HOME}/qemu_vm/ramdisk.img

	${QEMU} -machine accel=kvm,type=q35 -cpu host -m 2G -nographic -device virtio-net-pci,netdev=net0 -netdev user,id=net0,hostfwd=tcp::2222-:22 -drive if=virtio,format=qcow2,file=${UBUNTU} -drive if=virtio,format=qcow2,file=${BASE} -kernel ${KERNEL} -append "root=/dev/vda1 console=ttyS0"
}

function uvm_hl() {
	# local QEMU=${HOME}/src/qemu/build/qemu-system-x86_64
	local qemu_img=qemu-system-x86_64
	local backing_image=${HOME}/ubuntu_vm/backing.qcow2
	local user_data=${HOME}/ubuntu_vm/user-seed.img
	local kernel=${HOME}/src/linux-block/arch/x86/boot/bzImage
	local virtfs_path=/lib/modules/$(cat $DUMP_DIR/kernel.txt)
	local virtfs_args="-virtfs local,path=$virtfs_path,mount_tag=host_module,security_model=mapped,readonly"
	local nvme_cfg=${HOME}/ubuntu_vm/nvme0.cfg
	local nvme2_cfg=${HOME}/ubuntu_vm/nvme1.cfg
	local args

	args="--machine accel=kvm,type=q35 -cpu host -m 4G -smp cpus=4 --nographic "
	args+="-device virtio-net-pci,netdev=net0 -netdev user,id=net0,hostfwd=tcp::2222-:22 "
	args+="-drive if=virtio,format=qcow2,file=$backing_image,file.locking=off "
	args+="-drive if=virtio,format=qcow2,file=$user_data,file.locking=off "
	args+="$virtfs_args "
	# args+="-kernel ${KERNEL} -append \"root=/dev/vda1 console=ttyS0\" "
	args+="-readconfig $nvme_cfg "
	args+="-readconfig $nvme2_cfg "

	echo $args
	$qemu_img $args -kernel ${kernel} -append "root=/dev/vda1 console=ttyS0"
}

alias old_luvm="ssh -p 2222 ubuntu@0.0.0.0"

function uvm() {
	local QEMU=qemu-system-x86_64
	local BASE=${HOME}/ubuntu_vm/ubuntu-24.04-minimal-cloudimg-amd64.img
	local BACKING=${HOME}/ubuntu_vm/backing.qcow2
	local USER_DATA=${HOME}/ubuntu_vm/user-seed.img
	local ARGS

	ARGS="--machine accel=kvm,type=q35 -cpu host -m 4G -smp cpus=4 --nographic "
	ARGS+="-device virtio-net-pci,netdev=net0 -netdev user,id=net0,hostfwd=tcp::2222-:22 "
	ARGS+="-drive if=virtio,format=qcow2,file=$BACKING,file.locking=off "
	ARGS+="-drive if=virtio,format=qcow2,file=$USER_DATA,file.locking=off "
	ARGS+="-readconfig $HOME/ubuntu_vm/nvme.cfg"


	echo $ARGS
	$QEMU $ARGS
}
alias luvm="ssh -p 2222 ubuntu@0.0.0.0"

function lkml_mutt() {
	lei q -I https://lore.kernel.org/all/ -o ~/.mail/lore/mail/inbox --threads \
		--dedup=mid '(l:linux-block@vger.kernel.org OR \
		l:linux-kernel@vger.kernel.org OR l:linux-doc@vger.kernel.org OR \
		l:linux-nvme@lists.infradead.org OR l:linux-fsdevel@vger.kernel.org)\
		AND rt:1.week.ago..'
	neomutt -F ~/.mail/lore/muttrc
}

function reinsert_nvidia() {
	sudo modprobe -r nvidia-drm
	sudo modprobe -r nvidia-uvm
	sudo modprobe -r nvidia-modeset
	sudo modprobe -r nvidia
	lsmod | grep nvidia
	sudo modprobe ecdh_generic
	sudo modprobe ecc
	cd ~/src/public/open-gpu-kernel-modules/kernel-open/
	sudo insmod nvidia.ko
	sudo insmod nvidia-uvm.ko
	# sudo insmod nvidia-modeset.ko
	# sudo insmod nvidia-drm.ko
	lsmod | grep nvidia
}

PATH=$HOME/bin:/usr/local/cuda-13.0/bin:$PATH

if [ -e /usr/share/bash-completion/completions/git ]; then
	source /usr/share/bash-completion/completions/git
fi
