alias tmux="tmux -u"
alias vi="nvim"
alias vim="nvim"
alias bload="source ~/.bashrc"
alias bedit="vi ~/.bash_aliases ~/.bashrc"
alias cdl="cd /home/nitesh/src/linux"
# export NOTMUCH_CONFIG=$HOME/.lkml/notmuch.rc

function uvm() {
	local QEMU=/home/nitesh/src/qemu/build/qemu-system-x86_64
	local UBUNTU=/home/nitesh/qemu_vm/ubuntu-22.04-minimal-cloudimg-amd64.img 
	local BASE=/home/nitesh/qemu_vm/ubuntu.qcow2 
	local KERNEL=/home/nitesh/src/linux/arch/x86/boot/bzImage 
	local INITRD=/home/nitesh/qemu_vm/ramdisk.img	

	${QEMU} -machine accel=kvm,type=q35 -cpu host -m 2G -nographic -device virtio-net-pci,netdev=net0 -netdev user,id=net0,hostfwd=tcp::2222-:22 -drive if=virtio,format=qcow2,file=${UBUNTU} -drive if=virtio,format=qcow2,file=${BASE} -kernel ${KERNEL} -append "root=/dev/vda1 console=ttyS0"
}

alias login_uvm="ssh -p 2222 ubuntu@0.0.0.0" 

function lkml_mutt() {
	lei q -I https://lore.kernel.org/all/ -o ~/.mail/lore/mail/inbox --threads \
		--dedup=mid '(l:linux-block@vger.kernel.org OR \
		l:linux-kernel@vger.kernel.org OR l:linux-doc@vger.kernel.org OR \
		l:linux-nvme@lists.infradead.org OR l:linux-fsdevel@vger.kernel.org)\
		AND rt:1.week.ago..'
	neomutt -F ~/.mail/lore/muttrc
}

alias mymutt="cdl && neomutt -F ~/.lkml/muttrc"
PATH=$HOME/bin:$PATH
