alias tmux="tmux -u"
alias vi="nvim"
alias vim="nvim"
alias bload="source ~/.bashrc"
alias bedit="vi ~/.bash_aliases"
alias cdl="cd ~/src/linux"
alias cdf="cd ~/src/fio"
alias aptin="sudo apt install -y"
alias aptcs="sudo apt-cache search"
alias aptup="sudo apt update -y && sudo apt upgrade -y"
alias kernel_compile_install="time kernel_compile_install"

# export NOTMUCH_CONFIG=$HOME/.lkml/notmuch.rc

DUMP_DIR=${HOME}/dump

function kernel_install() {
	set -e
	sudo ls
	sudo make headers_install INSTALL_HDR_PATH=/usr
	sudo make modules_install INSTALL_MOD_STRIP=1
	sudo make install
	make kernelrelease > $DUMP_DIR/kernel.txt
	echo compiled kernel $(cat $DUMP_DIR/kernel.txt)
	echo booted kernel $(uname -r)
	set +e
}

function kernel_compile() {
	set -e
	make -j $(getconf _NPROCESSORS_ONLN)
	make kernelrelease > $DUMP_DIR/kernel.txt
	echo compiled_kernel ${cat $DUMP_DIR/kernel.txt}
	echo booted kernel $(uname -r)
	set +e
}

function kernel_reconfig() {
	sudo make distclean
	scripts/config --disable DEBUG_INFO
	scripts/config --disable SYSTEM_TRUSTED_KEYS
	scripts/config --disable SYSTEM_REVOCATION_KEYS
	scripts/config --disable DEBUG_INFO_BTF
	# scripts/config --disable HEADERS_INSTALL
	# scripts/config --disable SAMPLE_VFS
}

function kernel_compile_install() {
	kernel_compile
	kernel_install
}

function 22_uvm() {
	local QEMU=${HOME}/src/qemu/build/qemu-system-x86_64
	local UBUNTU=${HOME}/qemu_vm/ubuntu-22.04-minimal-cloudimg-amd64.img
	local BASE=${HOME}/qemu_vm/ubuntu.qcow2
	local KERNEL=${HOME}/src/linux/arch/x86/boot/bzImage
	local INITRD=${HOME}/qemu_vm/ramdisk.img

	${QEMU} -machine accel=kvm,type=q35 -cpu host -m 2G -nographic -device virtio-net-pci,netdev=net0 -netdev user,id=net0,hostfwd=tcp::2222-:22 -drive if=virtio,format=qcow2,file=${UBUNTU} -drive if=virtio,format=qcow2,file=${BASE} -kernel ${KERNEL} -append "root=/dev/vda1 console=ttyS0"
}

function uvm_hl() {
	local QEMU=${HOME}/src/qemu/build/qemu-system-x86_64
	local BASE=${HOME}/ubuntu_vm/ubuntu-24.04-minimal-cloudimg-amd64.img
	local BACKING=${HOME}/ubuntu_vm/backing.qcow2
	local USER_DATA=${HOME}/ubuntu_vm/user-seed.img
	local KERNEL=${HOME}/src/linux/arch/x86/boot/bzImage
	local NVME_CFG=${HOME}/ubuntu_vm/nvme.cfg
	local ARGS

	ARGS="--machine accel=kvm,type=q35 -cpu host -m 4G -smp cpus=4 --nographic "
	ARGS+="-device virtio-net-pci,netdev=net0 -netdev user,id=net0,hostfwd=tcp::2222-:22 "
	ARGS+="-drive if=virtio,format=qcow2,file=$BACKING,file.locking=off "
	ARGS+="-drive if=virtio,format=qcow2,file=$USER_DATA,file.locking=off "
	# ARGS+="-kernel ${KERNEL} -append \"root=/dev/vda1 console=ttyS0\" "
	ARGS+="-readconfig $NVME_CFG"


	echo $ARGS
	$QEMU $ARGS -kernel ${KERNEL} -append "root=/dev/vda1 console=ttyS0"
}

alias old_luvm="ssh -p 2222 ubuntu@0.0.0.0"

function uvm() {
	local QEMU=${HOME}/src/qemu/build/qemu-system-x86_64
	local BASE=${HOME}/ubuntu_vm/ubuntu-24.04-minimal-cloudimg-amd64.img
	local BACKING=${HOME}/ubuntu_vm/backing.qcow2
	local USER_DATA=${HOME}/ubuntu_vm/user-seed.img
	local ARGS

	ARGS="--machine accel=kvm,type=q35 -cpu host -m 4G -smp cpus=4 --nographic "
	ARGS+="-device virtio-net-pci,netdev=net0 -netdev user,id=net0,hostfwd=tcp::2222-:22 "
	ARGS+="-drive if=virtio,format=qcow2,file=$BACKING,file.locking=off "
	ARGS+="-drive if=virtio,format=qcow2,file=$USER_DATA,file.locking=off "
	ARGS+="-readconfig $HOME/ubuntu_vm/nvme.cfg"


	echo $ARGS
	$QEMU $ARGS
}
alias luvm="ssh -p 2222 ubuntu@0.0.0.0"

function lkml_mutt() {
	lei q -I https://lore.kernel.org/all/ -o ~/.mail/lore/mail/inbox --threads \
		--dedup=mid '(l:linux-block@vger.kernel.org OR \
		l:linux-kernel@vger.kernel.org OR l:linux-doc@vger.kernel.org OR \
		l:linux-nvme@lists.infradead.org OR l:linux-fsdevel@vger.kernel.org)\
		AND rt:1.week.ago..'
	neomutt -F ~/.mail/lore/muttrc
}

alias mymutt="cdl && neomutt -F ~/.lkml/muttrc"
PATH=$HOME/bin:$PATH
